### ISSUE TITLE
Compat with the Framed Blocks mod's item frame

### ISSUE THREAD

**Issue by Nathan-Fish** [mortuusars/Exposure#87]
Photos don't render in item frames from Framed Blocks the same way they do with vanilla item frames. A bug report on that mod for a number of discrepancies between the two item frames led me here for the remaining issue with pictures in these frames. 

from what I've gathered, the reason for the issue is that the framed blocks item frame is a block mimicking the default (entity) item frame, but there is hope since vanilla Minecraft maps along with other vanilla blocks that show up differently work as intended. 

Thoughts on bridging the gap? I love my photos and want them to find nice homes. 

Framed Blocks on Curseforge: https://www.curseforge.com/minecraft/mc-mods/framedblocks

Picture Demonstration. Same photo in different item frames
![Framed Frame](https://github.com/mortuusars/Exposure/assets/116105273/e3aa3d6d-6253-42d1-bebe-2c33ae0ba5ba)

**Comment by mortuusars** [comment]
I don't plan to add support for Framed Blocks frames currently. 
It would have required adding custom code specifically for their frames, since they are not using forge event for rendering (probably due to frames being blocks and not entities). If they used the event - it would have been working out of the box.

Besides, Rendering image in Item Frames was basically a placeholder. And most likely will be removed in the future because proper Photograph Frames were added in 1.7.0.
